### PR TITLE
feat: only support POST, PATCH, and PUT on secrets

### PR DESCRIPTION
**Pull request by djzager**
Instead of proxying any path passed to our service, we will only accept
requests to POST|PATCH|PUT on the routes associated with creating and
updating Secrets.

Although it's not immediately obvious how `r.Any(..)` could be misused,
it seems prudent to prevent it anyway.

### CODE REVIEW

**Comment by jmontleon** [comment]
LGTM. Is it sensible or feasible to do something similar with the reverse proxy? I think we will need OPTION for the short term to support CORS until the issue we're using it for is resolved. And I would assume also GET. I am not sure what we'd be cutting out in that case.

**Comment by mturley** [comment]
For the reverse proxy, the UI really only needs to make GET requests (and OPTIONS I guess while we have this workaround, which I still need to implement)

**Review by mturley — APPROVED** [review]
LGTM

**Comment by djzager** [comment]
Testing this change, here are the logs from the service:

```bash
$ kubectl logs -n openshift-migration pod/secret-service-7bd844bc5c-xsdsl -f
[GIN] 2022/03/24 - 19:59:56 | 201 |   36.419907ms |      10.217.0.1 | POST     "/api/v1/namespaces/openshift-migration/secrets"
[GIN] 2022/03/24 - 20:01:07 | 200 |   30.003434ms |      10.217.0.1 | PUT      "/api/v1/namespaces/openshift-migration/secrets/foo"
[GIN] 2022/03/24 - 20:01:43 | 415 |   15.285009ms |      10.217.0.1 | PATCH    "/api/v1/namespaces/openshift-migration/secrets/foo"
[GIN] 2022/03/24 - 20:02:07 | 415 |    32.89355ms |      10.217.0.1 | PATCH    "/api/v1/namespaces/openshift-migration/secrets/foo"
[GIN] 2022/03/24 - 20:03:01 | 200 |    7.395895ms |      10.217.0.1 | PATCH    "/api/v1/namespaces/openshift-migration/secrets/foo"
```

My `POST` Request:

```
$ curl -k \
-H "Authorization: Bearer $(oc whoami -t)" \
-H "Content-Type: application/json" \
-X POST \
-d '{"apiVersion":"v1","kind":"Secret","metadata":{"name":"foo"}}' \
https://secret-service-openshift-migration.apps-crc.testing/api/v1/namespaces/openshift-migration/secrets
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "namespace": "openshift-migration",
    "uid": "029289c2-ac37-43e5-bf17-1852da378dbd",
    "resourceVersion": "40416",
    "creationTimestamp": "2022-03-24T19:59:56Z"
  },
  "data": {
    "token": "IHNoYTI1Nn50RWd3ckgtVk1KbEE5Zk1OVlVmdTA0N2c2UFNlMGIzSkFwSjFiWHdqUnU4",
    "url": "aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj"
  },
  "type": "Opaque"
}
```

My PUT request:

```bash
$ curl -k \
-H "Authorization: Bearer $(oc whoami -t)" \
-H "Content-Type: application/json" \
-X PUT \
-d '{"apiVersion":"v1","kind":"Secret","metadata":{"name":"foo", "labels": {"foo": "bar"}}}' \
https://secret-service-openshift-migration.apps-crc.testing/api/v1/namespaces/openshift-migration/secrets/foo
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "namespace": "openshift-migration",
    "uid": "029289c2-ac37-43e5-bf17-1852da378dbd",
    "resourceVersion": "40707",
    "creationTimestamp": "2022-03-24T19:59:56Z",
    "labels": {
      "foo": "bar"
    },
  },
  "data": {
    "token": "IHNoYTI1Nn50RWd3ckgtVk1KbEE5Zk1OVlVmdTA0N2c2UFNlMGIzSkFwSjFiWHdqUnU4",
    "url": "aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj"
  },
  "type": "Opaque"
}% 
```

I messed up the PATCH request 2x (shown in the logs) by setting the wrong content-type, once fixed:

```bash
$ curl -k \
-H "Authorization: Bearer $(oc whoami -t)" \
-H "Content-Type: application/strategic-merge-patch+json" \
-X PATCH \
https://secret-service-openshift-migration.apps-crc.testing/api/v1/namespaces/openshift-migration/secrets/foo
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "namespace": "openshift-migration",
    "uid": "029289c2-ac37-43e5-bf17-1852da378dbd",
    "resourceVersion": "40707",
    "creationTimestamp": "2022-03-24T19:59:56Z",
    "labels": {
      "foo": "bar"
    }
  },
  "data": {
    "token": "IHNoYTI1Nn50RWd3ckgtVk1KbEE5Zk1OVlVmdTA0N2c2UFNlMGIzSkFwSjFiWHdqUnU4",
    "url": "aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj"
  },
  "type": "Opaque"
}% 
```

**Pull request merged**
